# 接口中文名
summary: 获取配置的专员与客户群
# 接口详细描述，将展示在接口文档顶部
description: 企业需要在管理后台或移动端中的「微信客服」-「升级服务」中，配置专员和客户群。该接口提供获取配置的专员与客户群列表的能力。
path: https://qyapi.weixin.qq.com/cgi-bin/kf/customer/get_upgrade_service_config
operationid: GetSpServiceConfig
tag: wwopenkfhlogic
method: GET
cate_path: 服务端API-微信客服-「升级服务」配置
# 表示权限说明，将会显示在接口的基本信息表格中
permission: >-
  企业需要使用[“微信客服”secret](#31106/如何开启API)所获取的accesstoken来调用（[accesstoken如何获取？](#10013/第三步：获取access_token)）<br>第三方应用需具有“微信客服权限->服务工具->配置「升级服务」”权限<br>代开发自建应用需具有“微信客服权限->服务工具->配置「升级服务」”权限
# request包含以下4种类型：
# auth 表示凭证参数
# params 表示get请求的query参数
# body 表示post请求的body参数
# formData 表示附件上下传接口中的附件数据
# 任意字段描述的基本类型(之后以baseType表示)：
# - name: string
#   example: string
#   type: number 1(string)|2(array)|3(object)|4(number)|5(file)|6(boolean)
#   description: 字段详细描述
#   is_required: boolean true|false
#   default: string 默认值，无特殊情况则为空
#   items: {}
#   如果items字段type为2(array类型)|3(object类型)时需要补充items的内容，当type为2时，只有第一个baseType生效，格式如下:
#   items:
#     properties:
#       baseType
request:
  auth:
    - name: access_token
      example: ACCESS_TOKEN
      type: 1
      description: ''
      is_required: true
      default: ''
  body: []
  params: []
  formData: []
# 以baseType的格式补充到body下
# - name: string
#   example: string
#   type: number 1(string)|2(array)|3(object)|4(number)|5(file)|6(boolean)
#   description: string 当前字段的详细描述
#   is_required: boolean true|false
#   default: string
#   items:
#     properties:
#       baseType
response:
  - status: '200'
    description: ''
    body:
      - name: errcode
        type: 4
        description: 返回码
        default: ''
        example: 0
        items: {}
      - name: errmsg
        type: 1
        description: 错误码描述
        default: ''
        example: ok
        items: {}
      - name: member_range
        type: 3
        description: 专员服务配置范围
        default: ''
        example: ''
        items:
          properties:
            - name: userid_list
              type: 2
              description: 专员userid列表
              default: ''
              example: ''
              items:
                properties:
                  - name: ''
                    is_required: false
                    description: ''
                    default: ''
                    example: zhangsan
            - name: department_id_list
              type: 2
              description: ''
              is_required: false
              default: ''
              example: ''
              items: {}
      - name: groupchat_range
        type: 3
        description: 客户群配置范围
        default: ''
        example: ''
        items:
          properties:
            - name: chat_id_list
              type: 2
              description: 客户群列表
              default: ''
              example: ''
              items:
                properties:
                  - name: ''
                    is_required: false
                    description: ''
                    default: ''
                    example: wraaaaaaaaaaaaaaaa
      - name: member_range.department_list
        example: ''
        type: 1
        description: 专员部门列表
        default: ''
# 注意事项，仅显示于接口的末尾
attention: ''
isExampleError: false
isInterface: true
